apiVersion: v1
kind: Service
metadata:
  name: todo-list-app-service
spec:
  type: NodePort
  selector:
    app: todo-list-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31991
